[package]
name = "petname"
version = "1.0.13"
authors = ["Gavin Panella <gavinpanella@gmail.com>"]
edition = "2018"
description = "Generate human readable random names. Usable as a library and from the command-line."
readme = "README.md"
repository = "https://github.com/allenap/rust-petname"
license = "Apache-2.0"
categories = ["command-line-utilities"]

[badges]
travis-ci = { repository = "allenap/rust-petname", branch = "master" }

[lib]
name = "petname"
path = "src/lib.rs"

[[bin]]
name = "petname"
path = "src/main.rs"
doc = false

[dependencies]
clap = "^2.33.0"
itertools = "^0.10.0"
rand = "^0.8.0"
